import React from 'react'
import { AppBar, Avatar, Box, Button, Card, CardContent, Chip, Container, Divider, List, ListItem, ListItemAvatar, ListItemText, Paper, Stack, styled, Tab, Tabs, Toolbar, Typography } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { PrismaClient } from '@prisma/client'
import Link from 'next/link'
import Header from '../components/layout/Header'
import * as XLSX from 'xlsx/xlsx.mjs';
import * as _ from 'lodash'
import LoadingOverlay from '../components/LoadingOverlay'

interface ServerProps {
}
export async function getServerSideProps() {
  const prisma = new PrismaClient()

  return {
    props: {}
  }
}

function TabPanel(props: any) {
  const { children, value, index, ...other } = props;

  return (
    <div
      role="tabpanel"
      hidden={value !== index}
      id={`simple-tabpanel-${index}`}
      aria-labelledby={`simple-tab-${index}`}
      {...other}
    >
      {value === index && (
        <Box sx={{ p: 3 }}>
          <Typography>{children}</Typography>
        </Box>
      )}
    </div>
  );
}

const Home: NextPage<ServerProps> = ({ }) => {

  const [tab, setTab] = React.useState('all')
  const [loading, setLoading] = React.useState(false)

  const handleTabChange = (event: any, newValue: any) => {
    setTab(newValue);
  };

  const onFileChange = async (event: any) => {
    try {
      setLoading(true)
      const file = event.target.files[0]
      const reader = new FileReader()
      reader.onload = (e: any) => {
        const bstr = e.target.result
        const workBook = XLSX.read(bstr, { type: "binary" })
        const workSheet = workBook.Sheets[workBook.SheetNames[0]]
        const fileData = XLSX.utils.sheet_to_json(workSheet, { header: 1 })
        const data = fileData.slice(1)
        console.log({ data })
      }
      reader.readAsBinaryString(file)
    } catch { }
    finally {
      setLoading(false)
    }
  }

  return (
    <>
      <LoadingOverlay visible={loading} />
      <Head>
        <title>Danh sách đơn hàng</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header title="Danh sách đơn hàng" />
      <Stack direction="row" alignItems="center" justifyContent="flex-end" sx={{ m: 2 }}>
        <Button variant="contained" component="label">
          Nhập file
          <input hidden multiple={false} type="file" onChange={onFileChange} />
        </Button>
      </Stack>
      <Box sx={{ borderBottom: 1, borderColor: 'divider' }}>
        <Tabs value={tab} onChange={handleTabChange} aria-label="basic tabs example">
          <Tab label="Tất cả" value='all' />
          <Tab label="Chờ giao vận chuyển" value='pending' />
          <Tab label="Đã giao vận chuyển" value='delivered' />
        </Tabs>
      </Box>
      <TabPanel value={'all'}>
        Item One
      </TabPanel>
      <TabPanel value={'pending'}>
        Item Two
      </TabPanel>
      <TabPanel value={'delivered'}>
        Item Three
      </TabPanel>
    </>
  )
}

export default Home
